Update migration instructions
The commands were missing the python module to run

```
docker-compose run web warehouse db upgrade head                                                             !10547
ERROR: Cannot start container 85ec2908a3ef2c3670bccdfab3beff6a72243c66a5e183462565431272642e13: [8] System error: exec: "warehouse": executable file not found in $PATH```