Fix 11 test failures revealed by pytest-randomly (#12733)
* Use pytest-randomly for tests

* Don't modify SecurityKeyGiveway globally in tests

Fixes the following when `make tests` is run with pytest-randomly:

    FAILED tests/unit/test_views.py::TestSecurityKeyGiveaway::test_default_response - AssertionError: assert <stub()> == {}

* Don't register stub as IOriginCache in tests

Fixes the following when `make tests` is run with pytest-randomly:

    FAILED tests/functional/test_basic.py::test_robots_txt[pypi.org-True] - AttributeError: 'stub' object has no attribute 'cache'
    FAILED tests/functional/test_basic.py::test_robots_txt[test.pypi.org-False] - AttributeError: 'stub' object has no attribute 'cache'
    FAILED tests/functional/test_caching.py::test_basic_views_dont_vary[/] - AttributeError: 'stub' object has no attribute 'cache'

* Stub `celery.Task.request_stack.top`

Fixes the following when `make tests` is run with pytest-randomly:

    FAILED tests/unit/test_tasks.py::TestWarehouseTask::test_after_return_closes_env_runs_request_callbacks - AttributeError: 'NoneType' object has no attribute 'top'
    FAILED tests/unit/test_tasks.py::TestWarehouseTask::test_after_return_without_pyramid_env - AttributeError: 'NoneType' object has no attribute 'top'
    FAILED tests/unit/test_tasks.py::TestWarehouseTask::test_reuses_request - AttributeError: 'NoneType' object has no attribute 'top'

* Use subset, not exact, match to test simple API

Fixes the following when `make tests` is run with pytest-randomly:

    FAILED tests/unit/api/test_simple.py::TestSimpleDetail::test_with_files_no_serial[application/vnd.pypi.simple.v1+html-None] - AssertionError: assert {'files': [{'...hyhujmwmfwfo'} == {'files': [{'...hyhujmwmfwfo'}

* Use subset, not exact, match to test malware check

Fixes the following when `make tests` is run with pytest-randomly:

    FAILED tests/unit/malware/test_checks.py::test_checks_subclass_base - AssertionError: assert 4 == 5

* Fix {JournalEntryFactory => JournalEntryFactory.create}

Fixes the following when `make tests` is run with pytest-randomly:

    FAILED tests/unit/admin/views/test_users.py::TestUserDelete::test_deletes_user - sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key...
    FAILED tests/unit/admin/views/test_users.py::TestUserDelete::test_deletes_user - sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider...

* Revert "Use pytest-randomly for tests"

This reverts commit 4f251ea4f54e29f1930ea7b1bd0d2d1a39668738.

* NFC: Remove unused `monkeypatch`

* Revert "Use subset, not exact, match to test malware check"

This reverts commit 65a8f7976a76a607c755cf079f6a5fe17bcf56a1.

* Clean up `FakeProjectCheck` after test

Co-authored-by: Dustin Ingram <di@users.noreply.github.com>