dev/test: handful of smallish fixes (#15680)
* test: remove unneeded fixtures

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

* feat(docs/dev): add make target for live reloading

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

* chore(dev): update to latest localstack release

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

* fix(dev): use correct scheduler for embedded beat

When running celery with the embedded `beat` process, passing the
scheduler must be the full parameter.

Resolves error seen in dev:

    AttributeError: 'PersistentScheduler' object has no attribute 'lock_key'

Signed-off-by: Mike Fiedler <miketheman@gmail.com>

---------

Signed-off-by: Mike Fiedler <miketheman@gmail.com>