lint: run mypy with correct Python 3.12 version
Previously not able to update, as `distutils` was removed from PYthon,
and mypy didn't know how to resolve the types from the vendored
`distutils` inside `setuptools`.

```console
warehouse/config.py:14: error: Cannot find implementation or library stub for module named "distutils" [import-not-found]
warehouse/config.py:14: note: See mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Instead of figuring that out, use a Pyramid built-in to coerce the
string to a boolean.

Refs: https://docs.pylonsproject.org/projects/pyramid/en/2.0-branch/api/settings.html#pyramid.settings.asbool
Refs: https://docs.pylonsproject.org/projects/pyramid/en/2.0-branch/_modules/pyramid/settings.html#asbool
Refs: https://github.com/pypa/setuptools/blob/477f713450ff57de126153f3034d032542916d03/setuptools/_distutils/util.py#L328-L341

Signed-off-by: Mike Fiedler <miketheman@gmail.com>