add rust toolchain to build and dev containers
a release of orjson caused `make deps` to start [failing unexpectedly](https://github.com/pypi/warehouse/actions/runs/12845424159/job/35819512078?pr=17451) with:

```
+ pip-compile --upgrade -o /tmp/tmp.VM3uXJx64Y/main.txt requirements/main.in
    error: subprocess-exited-with-error

    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [6 lines of output]
        Checking for Rust toolchain....

        Cargo, the Rust package manager, is not installed or is not on PATH.
        This package requires Rust and Cargo to compile extensions. Install it through
        the system's package manager or via https://rustup.rs/

        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
```

This adds the rust toolchain to our build intermediate container, and development container so that builds and dependency resolution can utilize it.